<?php 
DEFINE('MS_USER','root');
DEFINE('MS_HOST','70.38.38.114');
DEFINE('MS_PORT','3306');
DEFINE('MS_DBNAME','exportc');
DEFINE('MS_PASSWORD','102030');
DEFINE('MS_NAME_COMPANY','Scripts sas');

DEFINE('PG_USER','postgres');
DEFINE('PG_HOST','127.0.0.1');
DEFINE('PG_PORT','5432');
DEFINE('PG_DBNAME','test');
DEFINE('PG_PASSWORD','scripts2013');

DEFINE('ORACLE_USER', 'system');
DEFINE('ORACLE_HOST','192.168.1.12');
DEFINE('ORACLE_PASSWORD', 'scripts2013');
DEFINE('ORACLE_PORT', '1521');
DEFINE('ORACLE_SERVICE_NAME', 'XE');
DEFINE('ORACLE_DBNAME','test');
?>